// Generated by CoffeeScript 1.6.3
(function() {
  var config;

  config = {
    google: {
      returnURL: 'http://realizechange.herokuapp.com/auth/google/callback',
      realm: 'http://realizechange.herokuapp.com/'
    },
    twitter: {},
    mongoUrl: 'mongodb://localhost/realizeChange',
    title: 'RealizeChange.org',
    subtitle: 'Making dreams come true...'
  };

  module.exports = config;

}).call(this);
