// Generated by CoffeeScript 1.6.3
(function() {
  var config;

  config = {
    google: {
      returnURL: 'http://127.0.0.1:1337/auth/google/callback',
      realm: 'http://127.0.0.1:1337'
    },
    mongoUrl: 'mongodb://localhost/realizeChange',
    title: 'RealizeChange.org',
    subtitle: 'Making dreams come true...'
  };

  module.exports = config;

}).call(this);
