// Generated by CoffeeScript 1.6.3
(function() {
  var links;

  links = [
    {
      label: 'Rank Answers',
      key: 'front',
      path: '/answers'
    }, {
      label: 'Get Questions',
      key: 'about',
      path: '/questions'
    }, {
      label: 'Get Results',
      key: 'about',
      path: '/results'
    }, {
      label: 'Mission/Donate',
      key: 'about',
      path: '/mission'
    }
  ];

  module.exports = links;

}).call(this);
