// Generated by CoffeeScript 1.6.3
(function() {
  var links;

  links = [
    {
      label: 'Rank Answers',
      key: 'answers',
      path: 'partials/answers'
    }, {
      label: 'Get Questions',
      key: 'questions',
      path: 'partials/questions'
    }, {
      label: 'Get Results',
      key: 'results',
      path: 'partials/results'
    }, {
      label: 'Mission/Donate',
      key: 'mission',
      path: 'partials/mission'
    }
  ];

  module.exports = links;

}).call(this);
