// Generated by CoffeeScript 1.6.3
(function() {
  exports.index = function(req, res) {
    return res.render('index', {
      title: app.locals.config.title,
      subtitle: app.locals.config.subtitle
    });
  };

  exports.main = function(req, res) {
    return res.render('index', {
      title: app.locals.config.title,
      subtitle: app.locals.config.subtitle,
      username: req.user.name,
      200: 200
    });
  };

  exports.partials = function(req, res) {
    var renderObj;
    renderObj = {};
    renderObj.title = app.locals.config.title;
    renderObj.subtitle = app.locals.config.subtitle;
    renderObj.username = req.user.name;
    renderObj.routeName = req.params.name;
    return res.render("partials/" + req.params.name, renderObj);
  };

}).call(this);
