// Generated by CoffeeScript 1.6.3
(function() {
  exports.index = function(req, res) {
    return res.render('index', {
      title: app.locals.config.title,
      subtitle: app.locals.config.subtitle
    });
  };

  exports.main = function(req, res) {
    return res.render('index', {
      title: app.locals.config.title,
      subtitle: app.locals.config.subtitle,
      username: req.user.name,
      200: 200
    });
  };

  exports.partials = function(req, res) {
    var name, renderObj;
    name = req.params.name;
    renderObj = {
      title: app.locals.config.title,
      subtitle: app.locals.config.subtitle,
      routeName: name,
      200: 200
    };
    return res.render("partials/" + name, renderObj);
  };

}).call(this);
